<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 2/19/2015 at 11:42:33 AM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$name = addslashes($_POST['name']);
@$email = addslashes($_POST['email']);
@$phone = addslashes($_POST['phone']);
@$comment = addslashes($_POST['comment']);


// Validation
//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Inquiry";
$pfw_email_to = "info@bumsinc.net";
$pfw_message = "name: $name\n"
. "email: $email\n"
. "phone: $phone\n"
. "comment: $comment\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: messagesent.html");

?>
